Document: mjpg-streamer
Title: Debian mjpg-streamer Manual
Author: <insert document author here>
Abstract: This manual describes what mjpg-streamer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mjpg-streamer/mjpg-streamer.sgml.gz

Format: postscript
Files: /usr/share/doc/mjpg-streamer/mjpg-streamer.ps.gz

Format: text
Files: /usr/share/doc/mjpg-streamer/mjpg-streamer.text.gz

Format: HTML
Index: /usr/share/doc/mjpg-streamer/html/index.html
Files: /usr/share/doc/mjpg-streamer/html/*.html
